#If enabled, information on entities will be displayed.
"Display entities" = true
#If enabled, block image and name will be displayed.
"Display blocks" = true
#Change the HUD position when viewing blocks/entities. 0 for bottom, 1 for center, 2 for top.
#Range: 0 ~ 2
"HUD position" = 0

